/*
 * The MIT License
 *
 * Copyright (c) 2018 Niek Haarman
 * Copyright (c) 2007 Mockito contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
@file:Suppress("UNCHECKED_CAST")
package com.nhaarman.mockitokotlin2.internal

import org.mockito.ArgumentMatchers.*
import org.mockito.Mockito
import kotlin.reflect.KClass
import java.lang.reflect.Array as JavaArray

inline fun <reified T : Any> createInstance(): T {
    return createInstance(T::class)
}

//inline fun <reified T : Any?> createInstance(): T = when (T::class) {
//    String::class -> "" as T
//    Int::class -> Mockito.anyInt() as T
//    Boolean::class -> Mockito.anyBoolean() as T
//    Byte::class -> Mockito.anyByte() as T
//    Character::class -> Mockito.anyChar() as T
//    Long::class -> Mockito.anyLong() as T
//    Float::class -> Mockito.anyFloat() as T
//    Double::class -> Mockito.anyDouble() as T
//    Short::class -> Mockito.anyShort() as T
//    else -> createInstance(T::class)
//}

fun <T : Any> createInstance(kClass: KClass<T>?): T =
    when (kClass?.javaObjectType) {
        String::class.java -> "" as T // Mockito.anyString() as T does not work probably because of kotlin platform type
        Int::class.java -> Mockito.anyInt() as T
        Boolean::class.java -> Mockito.anyBoolean() as T
        Byte::class.java -> anyByte() as T
        Character::class.java -> Mockito.anyChar() as T
        Long::class.java -> Mockito.anyLong() as T
        Float::class.java -> Mockito.anyFloat() as T
        Double::class.java -> Mockito.anyDouble() as T
        Short::class.java -> Mockito.anyShort() as T
        else -> castNull()
    }

/**
 * Uses a quirk in the bytecode generated by Kotlin
 * to cast [null] to a non-null type.
 *
 * See https://youtrack.jetbrains.com/issue/KT-8135.
 */

private fun <T> castNull(): T = null as T
